# This code is designed to transform a chosen .yml file from heXRD into a .poni file readable by pyFAI
created: 2024 09  
creator: thomas stevens  

In [1]:
import yaml
import calibration_transform as CT

In [2]:
read_file = "Configuration"
path = "../"

In [3]:
with open(path + read_file + ".yml", 'r') as read_file:
    data = yaml.load(read_file, Loader=yaml.FullLoader)
    detectors = list(data['detectors'].keys())
    read_file.close()

In [6]:
for detector_name in detectors:
    heXRD_to_pyFAI = CT.HeXRDToPyFAI(detector_name, data)  # Initialising a class from the 'calibration_transforms.py' file
    heXRD_to_pyFAI.hexrd_to_pyfai_params()
    with open(path + detector_name + "_test.poni", 'w') as write_file:
        heXRD_to_pyFAI.write_poni(write_file)
        write_file.close()

[[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]]
[[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]]


In [5]:
import numpy as np
print(np.arcsin(0))

0.0
